package com.paperterritory.app
import android.content.Context
import android.graphics.*
import android.view.*
import kotlin.math.*
class GameView(c:Context,private val n:NetworkClient,private var s:GameState):View(c){private val bg=Paint().apply{color=Color.rgb(245,246,248)};private val p=Paint(1);private val l=Paint(1).apply{style=Paint.Style.STROKE;strokeCap=Paint.Cap.ROUND;strokeJoin=Paint.Join.ROUND};private val t=Paint(1);private var sx=0f;private var sy=0f;private var last=0L;private var pulse=0f
fun updateState(v:GameState){s=v;invalidate()}
override fun onDraw(c:Canvas){c.drawColor(bg.color);val z=min(width.toFloat()/s.width,(height-88f)/s.height)*.96f;val ox=(width-s.width*z)/2f;val oy=76f+(height-76f-s.height*z)/2f;fun X(v:Float)=ox+v*z;fun Y(v:Float)=oy+v*z;val by=s.players.associateBy{it.id};for((k,id)in s.cells){val q=k.split(',');val x=q.getOrNull(0)?.toIntOrNull();val y=q.getOrNull(1)?.toIntOrNull();val a=by[id];if(x!=null&&y!=null&&a!=null){p.color=Color.argb(225,Color.red(a.color),Color.green(a.color),Color.blue(a.color));c.drawRect(X(x*4f),Y(y*4f),X((x+1)*4f),Y((y+1)*4f),p)}};l.color=Color.rgb(215,219,224);l.strokeWidth=2.5f;c.drawRoundRect(X(0f),Y(0f),X(s.width.toFloat()),Y(s.height.toFloat()),8f,8f,l);for(a in s.players.filter{it.alive&&it.trail.size>1}){l.color=a.color;l.strokeWidth=7f;val path=Path();path.moveTo(X(a.trail[0].first),Y(a.trail[0].second));a.trail.drop(1).forEach{q->path.lineTo(X(q.first),Y(q.second))};c.drawPath(path,l)};pulse+=.12f;for(a in s.players.filter{it.alive}){p.color=a.color;c.drawCircle(X(a.x),Y(a.y),9f,p);if(a.id==s.selfId){l.color=Color.WHITE;l.strokeWidth=3f;c.drawCircle(X(a.x),Y(a.y),14f+sin(pulse)*1.5f,l)}};p.color=Color.argb(235,255,255,255);c.drawRoundRect(10f,10f,width-10f,66f,18f,18f,p);t.color=Color.rgb(35,38,44);t.textSize=18f;t.typeface=Typeface.DEFAULT_BOLD;c.drawText("TERRITORY",25f,35f,t);val me=s.players.firstOrNull{it.id==s.selfId};t.textSize=12f;t.typeface=Typeface.DEFAULT;c.drawText("AREA ${me?.area?:0}",25f,54f,t);t.textAlign=Paint.Align.RIGHT;c.drawText(if(s.room.isBlank())"ONLINE" else "ROOM ${s.room}",width-25f,35f,t);c.drawText("${s.players.count{it.alive}} PLAYERS",width-25f,54f,t);t.textAlign=Paint.Align.LEFT;p.color=Color.argb(220,255,255,255);c.drawRoundRect(12f,84f,190f,214f,14f,14f,p);s.players.sortedByDescending{it.area}.take(5).forEachIndexed{i,a->{t.color=if(a.id==s.selfId)a.color else Color.DKGRAY;t.textSize=12f;t.typeface=if(a.id==s.selfId)Typeface.DEFAULT_BOLD else Typeface.DEFAULT;c.drawText("${i+1}  ${a.name.take(12)}",24f,105f+i*24f,t)}};if(me?.alive==false){p.color=Color.argb(215,25,27,32);c.drawRoundRect(width/2f-120,height/2f-42,width/2f+120,height/2f+42,18f,18f,p);t.color=Color.WHITE;t.textAlign=Paint.Align.CENTER;t.textSize=22f;t.typeface=Typeface.DEFAULT_BOLD;c.drawText("ELIMINATED",width/2f,height/2f-4,t);t.textSize=13f;t.typeface=Typeface.DEFAULT;c.drawText("Respawning…",width/2f,height/2f+20,t);t.textAlign=Paint.Align.LEFT};postInvalidateDelayed(33)}
override fun onTouchEvent(e:MotionEvent):Boolean{when(e.actionMasked){MotionEvent.ACTION_DOWN->{sx=e.x;sy=e.y;return true};MotionEvent.ACTION_MOVE->{send(e.x-sx,e.y-sy);return true};MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->return true};return true}
private fun send(x:Float,y:Float){val now=System.currentTimeMillis();if(now-last<35)return;last=now;val z=hypot(x.toDouble(),y.toDouble()).toFloat();if(z>3)n.direction(x/z,y/z)}}