package com.paperterritory.app
import android.app.*;import android.os.Bundle;import android.graphics.Color;import android.view.*;import android.widget.*
class MainActivity:Activity(){private val n=NetworkClient()
private fun base()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(48,48,48,48);setBackgroundColor(Color.rgb(11,11,15))}
private fun b(t:String,a:()->Unit)=Button(this).apply{text=t;setOnClickListener{a()};textSize=17f;isAllCaps=false;layoutParams=LinearLayout.LayoutParams(-1,64).apply{setMargins(0,12,0,12)}}
override fun onCreate(x:Bundle?){super.onCreate(x);menu()}
private fun menu(){val v=base();v.addView(TextView(this).apply{text="TERRITORY";textSize=34f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;typeface=android.graphics.Typeface.DEFAULT_BOLD},LinearLayout.LayoutParams(-1,70));v.addView(TextView(this).apply{text="Claim ground. Cut trails. Survive.";setTextColor(Color.LTGRAY);gravity=Gravity.CENTER},LinearLayout.LayoutParams(-1,50));v.addView(b("PLAY ONLINE"){play(false,"")});v.addView(b("CREATE PRIVATE ROOM"){create()});v.addView(b("JOIN PRIVATE ROOM"){join()});v.addView(b("HOW TO PLAY"){help()});setContentView(v)}
private fun play(p:Boolean,r:String){n.connect("Player"+(100..999).random(),r,p,{s->runOnUiThread{setContentView(GameView(this,n,s))}},{m->runOnUiThread{Toast.makeText(this,m,Toast.LENGTH_LONG).show();menu()}})}
private fun create(){val c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789".toList().shuffled().take(5).joinToString("");AlertDialog.Builder(this).setTitle("Private room").setMessage("Room code: $c\nShare this code with friends.").setPositiveButton("ENTER"){_,_->play(true,c)}.setNegativeButton("CANCEL",null).show()}
private fun join(){val i=EditText(this).apply{hint="5-character room code";textSize=20f;gravity=Gravity.CENTER};AlertDialog.Builder(this).setTitle("Join private room").setView(i).setPositiveButton("JOIN"){_,_->val c=i.text.toString().trim().uppercase();if(c.length!=5)Toast.makeText(this,"Room codes are 5 characters.",Toast.LENGTH_SHORT).show()else play(true,c)}.setNegativeButton("CANCEL",null).show()}
private fun help(){AlertDialog.Builder(this).setTitle("How to play").setMessage("Drag anywhere to steer. Leave your territory to draw a trail, then return to your territory to fill the enclosed area. Crossing an exposed enemy trail eliminates them. Real-time matches are server-authoritative.").setPositiveButton("OK",null).show()}}
