package com.paperterritory.app
import android.app.*
import android.os.Bundle
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.view.Gravity
import android.widget.*
class MainActivity:Activity(){
 private val n=NetworkClient();private lateinit var economy:Economy
 private fun base()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(28,28,28,28);setBackgroundColor(Color.rgb(24,105,238))}
 private fun b(label:String,a:()->Unit)=Button(this).apply{text=label;setOnClickListener{a()};textSize=15f;isAllCaps=false;setTextColor(Color.WHITE);background=GradientDrawable().apply{setColor(Color.rgb(45,75,187));cornerRadius=30f;setStroke(2,Color.argb(80,255,255,255))};layoutParams=LinearLayout.LayoutParams(-1,60).apply{setMargins(0,5,0,5)}}
 override fun onCreate(x:Bundle?){super.onCreate(x);economy=Economy(this);menu()}
 private fun menu(){val v=base();v.addView(TextView(this).apply{text="TERRITORY";textSize=39f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;typeface=Typeface.DEFAULT_BOLD},LinearLayout.LayoutParams(-1,65));v.addView(TextView(this).apply{text="CLAIM • CUT • SURVIVE";setTextColor(Color.rgb(211,226,255));gravity=Gravity.CENTER},LinearLayout.LayoutParams(-1,30));v.addView(TextView(this).apply{text="🪙 ${economy.coins}     💎 ${economy.gems}";textSize=18f;setTextColor(Color.WHITE);gravity=Gravity.CENTER},LinearLayout.LayoutParams(-1,45));v.addView(b("PLAY ONLINE"){play(false,"","standard")});v.addView(b("1V1 DUEL"){play(false,"","duel")});v.addView(b("BOT GAME"){setContentView(BotGameView(this,economy){menu()})});v.addView(b("CREATE PRIVATE ROOM"){create()});v.addView(b("JOIN PRIVATE ROOM"){join()});v.addView(b("CHARACTERS & MYSTERY CRATE"){setContentView(ShopView(this,economy){menu()})});v.addView(b("HOW TO PLAY"){help()});setContentView(v)}
 private fun play(privateRoom:Boolean,room:String,mode:String){val holder=arrayOfNulls<GameView>(1);n.connect("Player"+(100..999).random(),room,privateRoom,mode,economy.selectedCharacter().id,{state->runOnUiThread{if(holder[0]==null){holder[0]=GameView(this,n,economy,state);setContentView(holder[0])}else holder[0]!!.updateState(state)}},{msg->runOnUiThread{Toast.makeText(this,msg,Toast.LENGTH_LONG).show();menu()}},{winner->runOnUiThread{if(holder[0]?.isSelf(winner)==true)setContentView(BonusGameView(this,economy){menu()})else menu()}})}
 private fun create(){val code="ABCDEFGHJKLMNPQRSTUVWXYZ23456789".toList().shuffled().take(5).joinToString("");AlertDialog.Builder(this).setTitle("Private room").setMessage("Room code: $code\nNormal 8-player mode.").setPositiveButton("ENTER"){_,_->play(true,code,"standard")}.setNegativeButton("CANCEL",null).show()}
 private fun join(){val input=EditText(this).apply{hint="5-character room code";textSize=20f;gravity=Gravity.CENTER};AlertDialog.Builder(this).setTitle("Join private room").setView(input).setPositiveButton("JOIN"){_,_->val code=input.text.toString().trim().uppercase();if(code.length!=5)Toast.makeText(this,"Room codes are 5 characters.",Toast.LENGTH_SHORT).show()else play(true,code,"standard")}.setNegativeButton("CANCEL",null).show()}
 private fun help(){AlertDialog.Builder(this).setTitle("How to play").setMessage("ONLINE: claim territory and cut exposed trails.\n\n1V1 DUEL: extra-large arena, opposite-side spawns, first to 35% territory or an elimination wins.\n\nBOT GAME: offline AI free-for-all.\n\nEvery player kill awards 15 coins. The winner enters the 6-second bonus game. Green +2 pickups add 2 seconds; coins and gems are collected normally.").setPositiveButton("OK",null).show()}
}