import http from"node:http";import{WebSocketServer}from"ws";import crypto from"node:crypto";
const M={standard:{w:180,h:120,c:4,max:8,target:100,s:.95},duel:{w:300,h:200,c:4,max:2,target:35,s:1.05}},COL=[[65,150,255],[255,78,96],[83,220,125],[190,95,255],[255,180,55],[40,210,210],[255,105,180],[170,210,70]],players=new Map(),rooms=new Map(),publicRoom={standard:null,duel:null},key=(x,y)=>x+","+y,cfg=p=>M[p.mode],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function spawn(p,i){const c=cfg(p);return p.mode==="duel"?{x:i%2?c.w-28:28,y:c.h/2}:{x:25+(i%4)*40,y:20+Math.floor(i/4)*35}}
function home(p){const c=cfg(p),r=p.mode==="duel"?5:6,cx=Math.floor(p.x/c.c),cy=Math.floor(p.y/c.c);for(let y=-r;y<=r;y++)for(let x=-r;x<=r;x++){const a=cx+x,b=cy+y;if(a>=0&&b>=0&&a<c.w/c.c&&b<c.h/c.c)p.cells.add(key(a,b))}}
function inside(p){const c=cfg(p);return p.cells.has(key(Math.floor(p.x/c.c),Math.floor(p.y/c.c)))}
function hit(x,y,tr){for(let i=1;i<tr.length;i++){const a=tr[i-1],b=tr[i],vx=b[0]-a[0],vy=b[1]-a[1],l=vx*vx+vy*vy,t=l?Math.max(0,Math.min(1,((x-a[0])*vx+(y-a[1])*vy)/l)):0,px=a[0]+t*vx,py=a[1]+t*vy;if(Math.hypot(x-px,y-py)<2.8)return true}return false}
function fill(p){const c=cfg(p),gw=c.w/c.c,gh=c.h/c.c;if(p.trail.length<2){p.trail=[];return}const block=new Set(p.cells),out=new Set(),q=[];for(let x=0;x<gw;x++)q.push([x,0],[x,gh-1]);for(let y=0;y<gh;y++)q.push([0,y],[gw-1,y]);for(let i=1;i<p.trail.length;i++){const a=p.trail[i-1],b=p.trail[i],n=Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/1.5));for(let j=0;j<=n;j++){const u=j/n,x=Math.floor((a[0]+(b[0]-a[0])*u)/c.c),y=Math.floor((a[1]+(b[1]-a[1])*u)/c.c);if(x>=0&&y>=0&&x<gw&&y<gh)block.add(key(x,y))}}while(q.length){const [x,y]=q.pop(),k=key(x,y);if(x<0||y<0||x>=gw||y>=gh||out.has(k)||block.has(k))continue;out.add(k);q.push([x+1,y],[x-1,y],[x,y+1],[x,y-1])}for(let y=0;y<gh;y++)for(let x=0;x<gw;x++)if(!out.has(key(x,y)))p.cells.add(key(x,y));p.trail=[]}
function finish(r,w){if(r.finished)return;r.finished=true;for(const id of r.members){const p=players.get(id);if(p?.ws.readyState===1)p.ws.send(JSON.stringify({type:"match_end",winnerId:w.id}))}}
function die(p){if(!p.alive)return;p.alive=false;p.trail=[];if(p.mode==="duel"){const r=rooms.get(p.room),w=r&&[...r.members].map(id=>players.get(id)).find(q=>q&&q!==p&&q.alive);if(w)finish(r,w);return}setTimeout(()=>{if(p.ws.readyState!==1)return;p.alive=true;const z=spawn(p,Math.floor(Math.random()*8));p.x=z.x;p.y=z.y;p.cells=new Set();home(p)},1200)}
function state(r,self){const c=M[r.mode],a=[...r.members].map(id=>players.get(id)).filter(Boolean),cells={};for(const p of a)for(const z of p.cells)cells[z]=p.id;return JSON.stringify({type:"state",width:c.w,height:c.h,selfId:self.id,room:r.id,mode:r.mode,targetPercent:c.target,privateRoom:r.privateRoom,players:a.map(p=>({id:p.id,name:p.name,x:p.x,y:p.y,r:p.color[0],g:p.color[1],b:p.color[2],area:p.cells.size,alive:p.alive,kills:p.kills,character:p.character,trail:p.trail.slice(-220)})),cells})}
function broadcast(){for(const r of rooms.values())for(const id of r.members){const p=players.get(id);if(p?.ws.readyState===1)p.ws.send(state(r,p))}}
const server=http.createServer((req,res)=>{res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({ok:true,players:players.size,rooms:rooms.size}))}),wss=new WebSocketServer({server});
wss.on("connection",ws=>{let p=null;ws.on("message",raw=>{try{const m=JSON.parse(raw);if(m.type==="join"&&!p){const mode=m.mode==="duel"?"duel":"standard";p={id:crypto.randomUUID(),name:String(m.name||"Player").slice(0,16),character:String(m.character||"blue").slice(0,24),ws,mode,x:0,y:0,dx:1,dy:0,color:COL[players.size%COL.length],cells:new Set(),trail:[],alive:true,kills:0,room:null};const z=spawn(p,players.size);p.x=z.x;p.y=z.y;home(p);players.set(p.id,p);let id=m.private?String(m.room||"").toUpperCase():publicRoom[mode];if(!id||!rooms.get(id)||rooms.get(id).members.size>=M[mode].max||rooms.get(id).finished){id=(mode==="duel"?"DUEL-":"PUBLIC-")+crypto.randomBytes(3).toString("hex");publicRoom[mode]=id}let r=rooms.get(id);if(!r){r={id,mode,members:new Set(),finished:false,privateRoom:Boolean(m.private)};rooms.set(id,r)}if(r.mode!==mode||r.members.size>=M[mode].max||r.finished)throw Error("Room is full or unavailable.");r.members.add(p.id);p.room=id;broadcast()}else if(m.type==="move"&&p){const x=Number(m.dx),y=Number(m.dy),l=Math.hypot(x,y);if(Number.isFinite(l)&&l>.01){p.dx=x/l;p.dy=y/l}}}catch(e){if(ws.readyState===1)ws.send(JSON.stringify({type:"error",message:e.message||"Server error."}))}});ws.on("close",()=>{if(!p)return;const r=rooms.get(p.room);if(r){r.members.delete(p.id);if(r.mode==="duel"&&!r.finished&&r.members.size===1){const w=players.get([...r.members][0]);if(w)finish(r,w)}if(!r.members.size){rooms.delete(r.id);if(publicRoom[p.mode]===r.id)publicRoom[p.mode]=null}}players.delete(p.id);broadcast()})});
setInterval(()=>{for(const p of players.values()){if(!p.room||!p.alive)continue;const r=rooms.get(p.room);if(!r||r.finished)continue;const c=cfg(p),before=inside(p);p.x=clamp(p.x+p.dx*c.s,1,c.w-1);p.y=clamp(p.y+p.dy*c.s,1,c.h-1);const after=inside(p);if(before&&!after)p.trail=[[p.x,p.y]];else if(!after&&p.trail.length){const z=p.trail[p.trail.length-1];if(Math.hypot(z[0]-p.x,z[1]-p.y)>1.5)p.trail.push([p.x,p.y])}else if(!before&&after)fill(p);if(p.trail.length>360){die(p);continue}if(p.cells.size>=Math.ceil((c.w/c.c)*(c.h/c.c)*c.target/100)){finish(r,p);continue}for(const o of players.values())if(o!==p&&o.room===p.room&&o.alive&&hit(p.x,p.y,o.trail)){p.kills++;die(o);break}if(r.finished)break}broadcast()},50);
const port=process.env.PORT||3000;server.listen(port,"0.0.0.0",()=>console.log("PaperTerritory server listening on "+port));